Repository coldsofttech/pym3u8downloader, pull requests merged in 2024-09, with the labels that each got.

#15 Fixed SSL Error Bug And Files Not Found in concatenate
  CHANGELOG.md
  README.md
  pym3u8downloader/__init__.py
  pym3u8downloader/__main__.py
Labels: bug

#19 Restructured Code + Add. Test Cases
  .github/workflows/pipeline.yml
  .gitignore
  CHANGELOG.md
  SECURITY.md
  pym3u8downloader/__init__.py
  pym3u8downloader/downloader.py
  pym3u8downloader/exceptions.py
  pym3u8downloader/utility_class.py
  pym3u8downloader/validations.py
  requirements.txt
  tests/index.js
  tests/package.json
  tests/test_m3u8downloader.py
  tests/test_utilityclass.py
Labels: enhancement

#20 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#21 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#23 Updated "download_master_playlist" to return JSON-formatted available resolutions
  CHANGELOG.md
  README.md
  SECURITY.md
  TROUBLESHOOTING.md
  pym3u8downloader/__init__.py
  pym3u8downloader/downloader.py
  pym3u8downloader/exceptions.py
  tests/test_m3u8downloader.py
Labels: enhancement
